using UnityEngine;
using UnityEngine.SceneManagement;
public class PlayerMovement : MonoBehaviour
{
    bool alive = true;

    public float speed = 5;

    public Rigidbody rb;

    float horizontalInput;

    public float horizontalMultiplier = 2;

    private void FixedUpdate()
    {
        if (!alive) return; 
        Vector3 fowardMove = transform.forward * speed * Time.deltaTime;
        Vector3 horizontalMove = transform.right * horizontalInput * speed * Time.fixedDeltaTime * horizontalMultiplier;
        rb.MovePosition(rb.position +  fowardMove + horizontalMove);
    }



    private void Update()
    {
        horizontalInput = Input.GetAxis("Horizontal"); 
        if (transform.position.y < -5) 
        {
            Die();
        }
    }

    public void Die() 
    {
        alive = false;
        SceneManager.LoadScene("Moriste"); 
    }


}
